# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  base = "./"
  publish = "./"
  # command = "npm run build"
  [build.environment]
    GIT_LFS_ENABLED = "1"
[[headers]]
  for="/*"
  [headers.values]
    Link = '''
      </css/styles/index.css>; rel=preload; as=style, \
      </css/js/index.js>; rel=preload; as=script, \
      </icons.svg>; rel=preload; as=image
    '''
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000"
    Content-Security-Policy = '''
      default-src 'self';
      img-src * blob: data:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.polyfill.io https://maps.googleapis.com/ https://www.googletagmanager.com https://www.google-analytics.com/analytics.js;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://www.youtube.com;
      connect-src 'self' https://www.vrmtel.net;
      font-src 'self' https://fonts.gstatic.com;
      media-src *;
      child-src 'self' https://www.youtube.com https://www.youtube-nocookie.com;
      frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com;
      worker-src 'self'
      block-all-mixed-content;
      upgrade-insecure-requests;
      disown-opener;
      reflected-xss block;
      manifest-src 'self';'''
# [[redirects]]
  # from = ""
  # to = ""
